### ISSUE TITLE
General Question about your efforts here

### ISSUE THREAD

**Issue by derek-adair** [mark-adams/docker-chromium-xvfb#1]
I'm new to selenium, docker, xvfb and sys admin stuff in general.  I find this project more clear to use than the [official selenium repo](https://github.com/SeleniumHQ/docker-selenium).  I've actually not been able to wrap my head around how to actually layer their project into my stack.  **This** project, however, is very intuitive to me and I was able to immediately look at your sample and figure it out.

So those are my reasons for *attempting* to build my own selenium-ready container...

What reasons do you have for not using the 'official' image?  

What are your future goals / plans for this project, if any?

Also, if possible, do you think you could explain the non-obvious differences between this project and that? (Dont need you to tell me you dont have FireFox, for example :p)

**Comment by mark-adams** [comment]
Hi @derek-adair,

Sorry that it took me so long to get around to this! For some reason I guess I missed the notification :cry: 

The official Selenium images seem more focused on running an entire Selenium cluster via Selenium Grid.

In my particular case, I was looking to easily build and run a Selenium-based test suite in a headless fashion using only a single container during CI builds. The official images didn't seem to be well suited for that so I built my own.

Currently, I provide a Python and Node-based image along with the platform-agnostic base image since those are the technologies that I primarily use in my day job but I certainly wouldn't mind adding additional images for other browsers or tech stacks in the future. PRs are always welcome. :smile: 

I think the main difference between the two projects is that my image is focused on a single container while the official images are focused on spinning up a cluster of servers to run the tests.

I hope that answered all of your questions. Feel free to re-open if you have more! :smiley:
